import { useState, useEffect } from "react";
import { api } from "../api";
import { useAuth } from "../context/AuthContext";
import { CATEGORIES } from "../data/questions";

export default function Setup({ onStart }) {
  const { user, logout } = useAuth();
  const [count, setCount] = useState(10);
  const [selectedCats, setSelectedCats] = useState([]);
  const [progress, setProgress] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    api.getProgress().then(setProgress).catch(() => {});
  }, []);

  const weakCategories = progress?.weakCategories || [];

  const toggleCat = (cat) => {
    setSelectedCats((prev) =>
      prev.includes(cat) ? prev.filter((c) => c !== cat) : [...prev, cat]
    );
  };

  const handleStart = async () => {
    setError("");
    setLoading(true);
    try {
      const focusCategories = selectedCats.length > 0
        ? weakCategories.filter((w) => selectedCats.includes(w.category))
        : weakCategories;

      const data = await api.generateQuestions(count, focusCategories, "google-ai-leadership");
      onStart({ questions: data.questions, count, categories: selectedCats });
    } catch (err) {
      setError("Could not generate questions. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="screen setup-screen">
      <div className="setup-topbar">
        <div>
          <div className="badge">Google AI Leadership Certification</div>
          <h1 className="title">Practice Flashcards</h1>
        </div>
        <div className="user-menu">
          <span className="user-email">{user?.email}</span>
          <button className="link-btn" onClick={logout}>Sign out</button>
        </div>
      </div>

      {progress && progress.totalSessions > 0 && (
        <div className="progress-banner">
          <div className="progress-banner-stats">
            <div className="pb-stat">
              <span className="pb-num">{progress.totalSessions}</span>
              <span className="pb-lbl">Sessions</span>
            </div>
            <div className="pb-stat">
              <span className="pb-num">
                {progress.latest
                  ? Math.round((progress.latest.score / progress.latest.total) * 100) + "%"
                  : "—"}
              </span>
              <span className="pb-lbl">Last score</span>
            </div>
            <div className="pb-stat">
              <span className="pb-num" style={{ color: weakCategories.length > 0 ? "var(--wrong)" : "var(--correct)" }}>
                {weakCategories.length}
              </span>
              <span className="pb-lbl">Weak areas</span>
            </div>
          </div>
          {weakCategories.length > 0 && (
            <p className="focus-note">
              AI will focus on: <strong>{weakCategories.map((w) => w.category).join(", ")}</strong>
            </p>
          )}
        </div>
      )}

      <div className="setup-card">
        <div className="field">
          <div className="field-header">
            <label className="field-label">Number of questions</label>
            <span className="field-value">{count}</span>
          </div>
          <input
            type="range" min={5} max={25} step={5} value={count}
            onChange={(e) => setCount(Number(e.target.value))}
            className="slider"
          />
          <div className="slider-labels"><span>5</span><span>25</span></div>
        </div>

        <div className="field">
          <label className="field-label">Focus on specific categories</label>
          <p className="field-hint">Leave all unselected to let the AI decide based on your weak areas.</p>
          <div className="category-grid">
            {CATEGORIES.map((cat) => {
              const weak = weakCategories.find((w) => w.category === cat);
              return (
                <button
                  key={cat}
                  className={`cat-chip ${selectedCats.includes(cat) ? "active" : ""}`}
                  onClick={() => toggleCat(cat)}
                >
                  {cat}
                  {weak && <span className="weak-badge">{weak.accuracy}%</span>}
                </button>
              );
            })}
          </div>
        </div>

        {error && <p className="auth-error" style={{ marginBottom: "1rem" }}>{error}</p>}

        <div className="setup-footer">
          <span className="pool-info">
            {loading ? "Generating adaptive questions…" : "Questions generated by AI based on your history"}
          </span>
          <button className="primary-btn" onClick={handleStart} disabled={loading}>
            {loading ? "Generating…" : "Start quiz →"}
          </button>
        </div>
      </div>
    </div>
  );
}
